export const words = [
    "algorithm", "array", "API", "application", "argument", "arithmetic", "async",
    "backend", "binary", "bit", "boolean", "branch", "break", "bug", "build", "byte",
    "cache", "callback", "camelCase", "class", "CLI", "closure", "cloud", "CMS",
    "code", "compile", "component", "constructor", "constant", "CPU", "CSS", "cursor",
    "data", "database", "debug", "declaration", "dependency", "deployment", "devops",
    "dictionary", "directive", "DOM", "driver", "DRY", "dynamic", "encryption",
    "endpoint", "entity", "enum", "environment", "exception", "expression", "export",
    "extend", "false", "fetch", "field", "file", "filter", "flag", "float", "flush",
    "for", "foreach", "framework", "frontend", "function", "garbage", "gateway",
    "getter", "git", "graph", "GUI", "hash", "heap", "host", "HTML", "HTTP",
    "identifier", "if", "import", "index", "inheritance", "init", "input", "instance",
    "int", "integer", "interface", "iteration", "JSON", "join", "jQuery", "Java",
    "JavaScript", "key", "keyword", "lambda", "library", "line", "link", "listener",
    "literal", "load", "local", "loop", "machine", "macro", "main", "map", "markup",
    "merge", "method", "middleware", "migration", "module", "mutable", "MySQL", "NaN",
    "namespace", "network", "node", "null", "number", "object", "OAuth", "operator",
    "option", "ORM", "output", "override", "package", "parameter", "parse", "patch",
    "path", "PHP", "pipe", "pixel", "pointer", "polling", "port", "POST", "print",
    "private", "procedure", "process", "program", "property", "prototype", "public",
    "Python", "query", "queue", "RAM", "React", "recursion", "refactor", "regex",
    "render", "repository", "request", "response", "REST", "return", "reverse",
    "revision", "root", "router", "runtime", "Ruby", "Rust", "sanitize", "SASS",
    "scope", "script", "SDK", "segment", "select", "server", "session", "setter",
    "shell", "singleton", "slice", "socket", "software", "source", "SQL", "stack",
    "statement", "static", "stream", "string", "structure", "style", "subclass",
    "super", "switch", "syntax", "tag", "target", "TCP", "template", "terminal",
    "thread", "throw", "token", "trace", "trait", "transaction", "tree", "true",
    "try", "tuple", "type", "UI", "undefined", "Unicode", "URL", "useEffect",
    "user", "UX", "value", "variable", "version", "virtual", "Vue", "web", "Webpack",
    "while", "widget", "window", "wrapper", "XML", "YAML", "yield", "zip"
];